version: '3.9'

services:
  mysql1:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: db1
    volumes:
      - /Users/kurtpagal/University/Year3/Fall-Term/CMPT-353/Assignments/CMPT-353-A3:/var/lib/mysql1
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  node1:
    build: .
    container_name: A3
    ports:
      - "80:8080"
    volumes:
      - /Users/kurtpagal/University/Year3/Fall-Term/CMPT-353/Assignments/CMPT-353-A3:/usr/src/app
    depends_on:
      mysql1:
        condition: service_started
    stdin_open: true
    tty: true